<a href="https://colab.research.google.com/github/fabiogitmelo/FVM_2023_Desafios/blob/main/3AnoTI_analise_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Baixar arquivo csv/ Dataset da internet e utilizar localmente.

2) Criar um dataframe com esse arquivo.

3) Contar, identificar e retornar a quantidade de linhas e colunas.

4) Renomear o nome de algumas colunas.

5) Fazer tratamento dos dados, retirando brancos e nulos.

6) Gerar/criar outro dataframe, e manipular/filtrar alguns dados.

7) Salvar o arquivo com o nome "analise_de_dados_seunome", e enviar por e-mail

In [12]:
# Importando a lib Pandas
import pandas as pd

In [14]:
# Lendo o arquivo csv
dataframe = pd.read_csv('sample_data/california_housing_test.csv')

In [16]:
# Contando linhas e colunas - atributo shape
dataframe.shape

(3000, 9)

In [17]:
# Identificando as colunas
dataframe.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [18]:
# Alterando o nome das colunas
dataframe.rename(columns={'Endereço de email': 'e-mail', 'Número de identificação': 'RA'}, inplace = True)

In [19]:
# Retornando as linhas - por default retorna 5 linhas
dataframe.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [22]:
# Criando outro dataframe filtrando por alguma(s) coluna(s)
lista_alunos = dataframe[['longitude', 'latitude', 'population']]

In [23]:
lista_alunos.shape

(3000, 3)

In [24]:
# Retornando as linhas - por default retorna 5 linhas
lista_alunos.head()

   longitude  latitude  population
0    -122.05     37.37      1537.0
1    -118.30     34.26       809.0
2    -117.81     33.78      1484.0
3    -118.36     33.82        49.0
4    -119.67     36.33       850.0

In [25]:
# Retornando as linhas - por default retorna 5 linhas
lista_alunos.head(31)

    longitude  latitude  population
0     -122.05     37.37      1537.0
1     -118.30     34.26       809.0
2     -117.81     33.78      1484.0
3     -118.36     33.82        49.0
4     -119.67     36.33       850.0
5     -119.56     36.51       663.0
6     -121.43     38.63       604.0
7     -120.65     35.48      1341.0
8     -122.84     38.40      1446.0
9     -118.02     34.08      2830.0
10    -118.24     33.98      1288.0
11    -119.12     35.85       564.0
12    -121.93     37.25       535.0
13    -117.03     32.97      1935.0
14    -117.97     33.73      1217.0
15    -117.99     33.81       157.0
16    -120.81     37.53       189.0
17    -121.20     38.69      1603.0
18    -118.88     34.21       654.0
19    -122.59     38.01      3450.0
20    -122.15     37.75       849.0
21    -121.37     38.68       937.0
22    -118.16     34.07      1651.0
23    -122.20     37.79      1410.0
24    -117.28     33.28      4049.0
25    -118.03     34.16       667.0
26    -122.42     37.76      2259.0
27    -118.39     33.99      1030.0
28    -118.45     34.07      3751.0
29    -118.48     34.01      1561.0
30    -119.35     36.33       568.0

In [26]:
#Removendo 1 linha - “1” seria o índice da linha e “index” seria o eixo de remoção, no caso uma linha.
lista_alunos=lista_alunos.drop(29)

In [27]:
lista_alunos

      longitude  latitude  population
0       -122.05     37.37      1537.0
1       -118.30     34.26       809.0
2       -117.81     33.78      1484.0
3       -118.36     33.82        49.0
4       -119.67     36.33       850.0
...         ...       ...         ...
2995    -119.86     34.42      1258.0
2996    -118.14     34.06      3496.0
2997    -119.70     36.30       693.0
2998    -117.12     34.10        46.0
2999    -119.63     34.42       753.0

[2999 rows x 3 columns]

In [28]:
#Removendo 1 linha - “1” seria o índice da linha e “index” seria o eixo de remoção, no caso uma linha.
lista_alunos=lista_alunos.drop(30)

In [29]:
lista_alunos

      longitude  latitude  population
0       -122.05     37.37      1537.0
1       -118.30     34.26       809.0
2       -117.81     33.78      1484.0
3       -118.36     33.82        49.0
4       -119.67     36.33       850.0
...         ...       ...         ...
2995    -119.86     34.42      1258.0
2996    -118.14     34.06      3496.0
2997    -119.70     36.30       693.0
2998    -117.12     34.10        46.0
2999    -119.63     34.42       753.0

[2998 rows x 3 columns]